images:
  cos-stable:
    image_regex: cos-stable-60-9592-84-0
    project: cos-cloud
    metadata: "user-data</go/src/github.com/containerd/cri/test/e2e_node/init.yaml,containerd-configure-sh</go/src/github.com/containerd/cri/cluster/gce/configure.sh,containerd-extra-init-sh</go/src/github.com/Random-Liu/runsc-scripts/runsc-node-e2e-init.sh,containerd-env</go/src/github.com/Random-Liu/runsc-scripts/env-mc,gci-update-strategy=update_disabled"
